/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEBAS
 */
public class Ejercicio1 extends javax.swing.JFrame {
Femenino fem = new Femenino();
Masculino mas = new Masculino();
Elefante ele = new Elefante();

ArrayList <Persona> ARRAY = new ArrayList<Persona>();
ArrayList <Elefante> ARRAY_ELEFANTE = new ArrayList<Elefante>();
DefaultTableModel model;
    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
        
        String columnas[]={"MASCULINO","FEMENINO","ELEFANTE"};
        String matriz[][]={};
        model=new DefaultTableModel(matriz,columnas);
        tabla.setModel(model);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jButton1.setText("GENERAR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        JOptionPane.showMessageDialog(null,"INFORMACION MASCULINO","MASCULINO",1);
        String n=JOptionPane.showInputDialog(null, "INGRESE NOMBRE DE MASCULINO", "INGRESE", 1);
        String r=JOptionPane.showInputDialog(null,"INGRESE RELIGION DE PERSONA","INGRESE",1);
        int e=Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE EDAD DE MASCULINO", "EDAD",1));
        String u=JOptionPane.showInputDialog(null, "INGRESE UNIVERIDAD DEL ESTUDIANTE MASCULINO", "INGRESE",1);
        
        mas.setNombrePERSONA(n);
        mas.setReligionPERSONA(r);
        mas.setEdad(e);
        mas.setUniversidad(u);
        
        ARRAY.add(mas);
        
        JOptionPane.showMessageDialog(null,"INFORMACION FEMENINO","FEMENINO",1);
        
        String n1=JOptionPane.showInputDialog(null, "INGRESE NOMBRE DE FEMENINO", "INGRESE", 1);
        fem.setNombrePERSONA(n1);
        String r1=JOptionPane.showInputDialog(null,"INGRESE RELIGION DE PERSONA","INGRESE",1);
        fem.setReligionPERSONA(r1);
        String a=JOptionPane.showInputDialog(null, "CUAL ES SU MEJOR AMIGA", "INGRESE", 1);
        fem.setAmiga(a);
        int e1=Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE EDAD DE FEMENINO", "EDAD",1));
        fem.setEdad(e1);
        
        ARRAY.add(fem);
        
        JOptionPane.showMessageDialog(null,"INFORMACION ELEFANTE","ELEFANTE",1);
        String es=JOptionPane.showInputDialog(null, "INGRESE EL NOMBRE DE LA ESPECIE","INGRESE",1);
        ele.setEspecie(es);
        int edad=Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE EDAD DE ELEFANTE", "EDAD",1));                    
        ele.setEdad(edad);
        
        ARRAY_ELEFANTE.add(ele);
                
        //LIMPIAR LA TABLA Y PARA NO REPETIR
           for (int i = 0; i <tabla.getRowCount(); i++) {
             model.removeRow(i);
           } 
        
            model.addRow(new Object[]{ARRAY.get(0).getNombrePERSONA(), ARRAY.get(1).getNombrePERSONA(), ARRAY_ELEFANTE.get(0).getEspecieElefante()});
            model.addRow(new Object[] {ARRAY.get(0).getEdadMamifero(), ARRAY.get(1).getEdadMamifero(), ARRAY_ELEFANTE.get(0).getEdadMamifero()});
            model.addRow(new Object[] {ARRAY.get(0).getReligionPERSONA(), ARRAY.get(1).getReligionPERSONA(), "********"});
            model.addRow(new Object[] {"********", ARRAY.get(1).getAmiga(), "********"});
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
